//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemLessonStorage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemLessonContext : DbContext
    {
        public SystemLessonContext()
            : base("name=SystemLessonContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Specialtys> Specialtys { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<TeacherDisciplines> TeacherDisciplines { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
