//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemLessonStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherDisciplines
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public int DisciplineId { get; set; }
        public int AcademicYearStart { get; set; }
        public int AcademicYearEnd { get; set; }
        public int GroupId { get; set; }
        public int TotalHours { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
