//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemLessonStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public int GroupId { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
